Added more indication in help section Fix various bugs

diff --git a/sg b/sg
--- a/sg
+++ b/sg
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/bash -x
 
 [ -e ~/.sgcli ] && SG_URL=`cat ~/.sgcli | sed -En 's/^SG_URL *= *//p'`
 [ -e ~/.sgcli ] && TOKEN=`cat ~/.sgcli | sed -En 's/^TOKEN *= *//p'`
@@ -8,7 +8,7 @@
 verb=$1
 
 function _help {
-    cat $0 | sed -n -E "/^function _(.*) {/{ s/function _(.*) {/\1/; s/_/ /g;p; }"
+    cat $0 | sed -n -E "/^function _(.*) { *#.+#.*/{ s,function _(.*) { *# *(.*)# *(.*),\1 : \2 : $0 \1 \3,; s/_/ /g;p; }" | column -t -s ":"
 }
 
 [ "$verb" == "help" ] && { _help; exit 0; }
@@ -17,31 +17,20 @@ function _help {
     read -p "StorageGRID URL : " SG_URL \
     && echo "SG_URL = $SG_URL" >> ~/.sgcli
 
-
-
-
-function _user_show {
-
-    curl -s -k -X GET "$SG_URL/org/users" \
-            -H "accept: application/json" \
-            -H "Content-Type: application/json" \
-            -H "X-Csrf-Token: 7eabc2e29cbad36137bb58e767f39ce9" \
-            -H "Authorization: Bearer $TOKEN" | jq -r '.data[] | .uniqueName + " " + .id + " " + .userURN' | column -t
+function _user_list { _user_show "$@"; }
+function _user_show { # List all defined users #
+    curl -s -k -X GET "$SG_URL/org/users" "${HEADER[@]}" | jq -r '.data[] | .uniqueName + " " + .id + " " + .userURN' | column -t
 }
 
-function _user_get {
+function _user_get { # Get a specific user # <userid>
     [ -z $1 ] && { 
         echo "`echo $0"${SG_CLI_FUNCTION}"|tr "_" " "` ${verb} <userid>"; exit 0; 
         }
 
-    curl -s -k -X GET "$SG_URL/org/users/$1" \
-        -H "accept: application/json" \
-        -H "Content-Type: application/json" \
-        -H "X-Csrf-Token: 7eabc2e29cbad36137bb58e767f39ce9" \
-        -H "Authorization: Bearer $TOKEN" | jq -r '.data'
+    curl -s -k -X GET "$SG_URL/org/users/$1" "${HEADER[@]}" | jq -r '.data'
  
 }
-function _user_create {
+function _user_create { # Create a user # <username> <full name> [<group_id_1> <group_id_2> ...]
 
     [ -z $1 ] && { 
         echo "`echo $0"${SG_CLI_FUNCTION}"|tr "_" " "` ${verb} <username> <full name>";
@@ -62,39 +51,28 @@ function _user_create {
         done
     fi
 
-    [ -n $groups ] && group_json="\"memberOf\": [\"$groups\"],"
+    [ -n "$groups" ] && group_json="\"memberOf\": [\"$groups\"],"
 
-    curl -s -k -X POST "$SG_URL/org/users" \
-            -H "accept: application/json" \
-            -H "Content-Type: application/json" \
-            -H "X-Csrf-Token: 7eabc2e29cbad36137bb58e767f39ce9" \
-            -H "Authorization: Bearer $TOKEN" \
+    curl -s -k -X POST "$SG_URL/org/users" "${HEADER[@]}" \
             -d "{ \"fullName\": \"$fullName\", $group_json \"disable\": false, \"uniqueName\": \"user/$unique\"}" | jq -r '. | "\( .code ) " + .status,.data.id'
 
 }
 
-function _user_delete {
+function _user_delete { # Deletes a user by UUID # <userid>
     [ -z $1 ] && { 
         echo "`echo $0"${SG_CLI_FUNCTION}"|tr "_" " "` ${verb} <userid>"; exit 0; 
         }
     
     id=$1
 
-    curl --fail -k -X DELETE "$SG_URL/org/users/$id" \
-            -H "accept: application/json" \
-            -H "Content-Type: application/json" \
-            -H "X-Csrf-Token: 7eabc2e29cbad36137bb58e767f39ce9" \
-            -H "Authorization: Bearer $TOKEN" && echo "Success" || echo "Error"
+    curl --fail -k -X DELETE "$SG_URL/org/users/$id" "${HEADER[@]}" && echo "Success" || echo "Error"
 
 }
 
-function _group_show {
+function _group_show { # List all defined groups #
 
     curl -s -k -X GET "$SG_URL/org/groups" \
-            -H "accept: application/json" \
-            -H "Content-Type: application/json" \
-            -H "X-Csrf-Token: 7eabc2e29cbad36137bb58e767f39ce9" \
-            -H "Authorization: Bearer $TOKEN" | jq -r '.data[] | .uniqueName + " " + .id + " " + .groupURN' | column -t
+            $HEADER | jq -r '.data[] | .uniqueName + " " + .id + " " + .groupURN' | column -t
 }
 
 function authenticate {
@@ -116,7 +94,7 @@ function authenticate {
         -d "{ \"accountId\": \"$TENANT\", \"username\": \"$USER\", \"password\": \"$PASS\", \"cookie\": true, \"csrfToken\": false}" \
         | sed -E 's/.*"data":"([^"]+)".*/\1/'`
 
-    grep -E "^TOKEN *=.*" ~/.sgcli && sed -E -i.tmp "s/^TOKEN *=.*/TOKEN = $TOKEN/" ~/.sgcli || echo "TOKEN = $TOKEN" >> ~/.sgcli
+    grep -E "^TOKEN *=.*" ~/.sgcli && sed -E -i.tmp "s/^TOKEN *=.*/TOKEN = $TOKEN/" ~/.sgcli || { echo "TOKEN = $TOKEN" >> ~/.sgcli; }
 }
 
 [ -z "$TOKEN" -o "x22" == "x$( curl --fail -s -k -X GET "$SG_URL/org/users" \
@@ -125,6 +103,7 @@ function authenticate {
             -H "X-Csrf-Token: 7eabc2e29cbad36137bb58e767f39ce9" \
             -H "Authorization: Bearer $TOKEN"; echo $?; )" ] && authenticate
 
+HEADER=("-H" 'accept: application/json' "-H" 'Content-Type: application/json' "-H" 'X-Csrf-Token: 7eabc2e29cbad36137bb58e767f39ce9' "-H" "Authorization: Bearer $TOKEN")
 
 type ${SG_CLI_FUNCTION}_$verb &> /dev/null
 
@@ -134,5 +113,6 @@ then
     ${SG_CLI_FUNCTION}_$verb "$@"
 else
     shift
+    [ "x$*" == "x" ] && { echo "Invalid argument" 1>&2; exit 1; }
     SG_CLI_FUNCTION=${SG_CLI_FUNCTION}_$verb $0 "$@"
 fi
